### ISSUE TITLE
Parsing scv error

### ISSUE THREAD

**Issue by ghost** [NupurBhaisare/Cup-and-disc-segmentation-for-glaucoma-detection-CDR-Calculation-#1]
Hello thank you very much for your work and providing source code about cup and disc segmentation. But I have problem here, I tried to run Glaucoma_detection.py it showed me error code like this :

```
Traceback (most recent call last):
  File "Glaucoma_detection.py", line 312, in <module>
    X_test = pd.read_csv('E:/Term Project 01/x1.csv', header=None, delim_whitespace=True)
  File "C:\Users\nvidia\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\nvidia\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\nvidia\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\nvidia\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\nvidia\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
File "pandas\_libs\parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

then I checked all the csv files, suddenly csv a, b, c, d, x1 and y1 became empty. I followed your intructions about putting the exact dataset folder right into source code file etc.

**Comment by NupurBhaisare** [comment]
Hey....I'll check the error and update you about it or if the files have a problem I'll update them.
